--------------------------------------------------------
--  File created - Wednesday-June-27-2018   
--------------------------------------------------------
DROP TABLE "EDWARDORA"."CLINIC" cascade constraints;
--------------------------------------------------------
--  DDL for Table CLINIC
--------------------------------------------------------

  CREATE TABLE "EDWARDORA"."CLINIC" 
   (	"PERSON_ID" NUMBER(*,0), 
	"TYPE_ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(99 BYTE), 
	"LAST_NAME" VARCHAR2(99 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into EDWARDORA.CLINIC
SET DEFINE OFF;
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (33433,1,'JOHNSONA','ABCDE');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015107159,1,'JERICA','TUBALLA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015106152,1,'JUSTIN JASON','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015111028,1,'CARL JUSTINE','DOLLETE');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015107415,1,'RENZ JIRHEL','BAHIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015151411,1,'GUILLERMO','HEQUIBAL');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015111989,1,'GIESTHER','GAPASANGRA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015111963,1,'JOSE ANGEL','CARLOS');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015120485,1,'ANGELO IAN','REYES');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015107654,1,'JADE LUKE','DIAZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015104643,1,'NELBEIN PAUL','NONO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015112905,1,'KHIER BENNEDIC CYREL','FLORES');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015140237,1,'GLENN CLARENCE','LABO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015111297,1,'PAULINE ANDREA','VIVERO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015170909,1,'RENZ','GAZMIN');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015111308,1,'PAULO DANIEL','CARANDANG');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015107941,1,'ELLY JAY','GRAN');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015110102,1,'JOHN JEFCAR','OMAOENG');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2015107361,1,'GWYNEL DANIEL','SAMBILE');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000000,2,'ARESH','SHAHARKIZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000001,2,'ERIC','BLANCAFLOR');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000002,2,'JOEL','DE GOMA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000003,2,'FUENTES','GLOREN');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000005,2,'MEL','LLESOL');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000006,2,'MARY JANE','SAMONTE');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000007,2,'ELCID','SERRANO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000008,2,'LARRU','VEA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000009,2,'JOHN PAUL','TOMAS');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000010,2,'WILLIAM','REY');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (10000011,2,'VIDA MARIE','MARAYAG');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000000,2,'EDNA','CORTEZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000001,2,'PADILLA','REYNALDO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000002,2,'ARVIN','PATANI');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000003,2,'NEIL EDWIN','YUZON');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000004,2,'MARIA THERESA','TRINIDAD');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000005,2,'GENEVIEVE','ACIO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000006,2,'ANN MILLAINE','AMBAYEC');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000007,2,'LABAYO','CZARINA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (20000008,2,'SALUSTIANO','MACATANGAY');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (331244,1,'NICOLE','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2214,1,'NICOLE','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (31111111,2,'JUANITOUH','GRACIAZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (12345678,1,'Nicole','Tianco');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (313132,2,'sdfsf','qwe3we');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2,1,'2','2');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (56757745131,1,'56757745131','56757745131');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (567577451312,1,'567577451312','567577451312');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (1414466,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (14144661,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (141446,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2425,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2426,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2427,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2428,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (2429,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (3000,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (42353,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (42352,1,'EDWARD','GARCIA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (60601,1,'60601','60601');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (60602,1,'60602','60602');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (60603,1,'60603','60603');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (60604,1,'60604','60604');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (60605,1,'60605','60605');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (1246,1,'1246','1246');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (12567,1,'ANGEL','DEVIL');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (12578,1,'angel','devil');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (4235,2,'4235','4235');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (4444,2,'ABCD','EFGH');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (1,2,'JEJEMONZ','LOPEZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (111111111,2,'GUGU','GAGA');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (3333,2,'AAA','BBB');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (444,1,'FF','GG');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (12134556,1,'12134556','12134556');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (121345561,1,'12134556','12134556');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (1000331,1,'1000331','1000331');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (1121237,1,'Edward','Garcia');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (7281164,1,'NICOLE','DELACRUZ');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (862365,1,'james','isaac');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (13113,1,'james','isaac');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (991831,1,'MICHELLE','DELAFUENTE');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (312,2,'ADMIN','ADMIN');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (3112,2,'ELIZA','SOBERANO');
Insert into EDWARDORA.CLINIC (PERSON_ID,TYPE_ID,FIRST_NAME,LAST_NAME) values (24234,2,'ed','garcia');
--------------------------------------------------------
--  DDL for Index SYS_C007874
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDWARDORA"."SYS_C007874" ON "EDWARDORA"."CLINIC" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRI_PRACTICAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EDWARDORA"."TRI_PRACTICAL" 
AFTER INSERT OR UPDATE OR DELETE ON CLINIC
FOR EACH ROW

BEGIN
IF INSERTING THEN DBMS_OUTPUT.PUT_LINE('YOU INSERTED SOMETHING DID YOU NOT?');
ELSIF UPDATING THEN DBMS_OUTPUT.PUT_LINE ('WHAT DID YOU UPDATE THIS TIME?'||:OLD.FIRST_NAME||' '||:NEW.FIRST_NAME);
ELSIF DELETING THEN DBMS_OUTPUT.PUT_LINE ('JUST LIKE OUR RELATIONSHIP... YOU DELETED IT');
END IF;
END;
/
ALTER TRIGGER "EDWARDORA"."TRI_PRACTICAL" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DBMS_OUTPUT
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DBMS_OUTPUT" FOR "SYS"."DBMS_OUTPUT";
--------------------------------------------------------
--  Constraints for Table CLINIC
--------------------------------------------------------

  ALTER TABLE "EDWARDORA"."CLINIC" ADD PRIMARY KEY ("PERSON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EDWARDORA"."CLINIC" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDWARDORA"."CLINIC" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "EDWARDORA"."CLINIC" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EDWARDORA"."CLINIC" MODIFY ("PERSON_ID" NOT NULL ENABLE);
